### ISSUE TITLE
Some minor graphics glitches on macOs

### ISSUE THREAD

**Issue by castal** [sanderland/katrain#52]
The settings panels are garbled by overprinting:
<img width="605" alt="General and Engine Settings" src="https://user-images.githubusercontent.com/9596277/83662870-b8f11300-a58d-11ea-9206-2dd54223fb76.png">

The "Setup New Game" panel has a problem with some of the values not printing entirely inside the boxes:
<img width="406" alt="Setup New Gaame" src="https://user-images.githubusercontent.com/9596277/83663199-2735d580-a58e-11ea-8ae4-47607d08e346.png">

Furthermore, when I click on the value "7" to change the number of handicap stones, it is the "komi" field that is selected. To select and change the handicap value I have to click above on the board size field.

**Comment by sanderland** [comment]
Wow, that's umm interesting! I suspect this is caused by display-dependent sizing

**Comment by sanderland** [comment]
@castal please try the 1.1.1 branch update I pushed just now. On my computer
```

**Comment by castal** [comment]
I didn't resize the katrain window before taking the screen shots, and it
still occurs after resizing. I hadn't seen this problem in the previous
version.

I'll look into the 1.1.1 branch and get back to you. By the way, I also
pm'ed you on reddit.

**Comment by castal** [comment]
OK, that did the trick! There is still some overwriting, and the actual image seems to be only half the size shown here, and consequently a bit hard to read:
![General Settings](https://user-images.githubusercontent.com/9596277/83670021-1ab67a80-a598-11ea-94cf-323ffc13e3c2.png)

**Comment by sanderland** [comment]
Had another idea, try once more?
